# Site
repository: camigil
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Camila Gil
title: Software Developer
email: cg.camilagil@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  camigil
linkedin_username: camila-gil

# Additional icon links
additional_links:
- title: My CV
  icon: fas fa-file
  url: https://drive.google.com/file/d/1EJDFRzbAByIgtzCkVbkAnYoM9Aj_mDlB/view?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: cami.jpeg
about_content: | # this will include new lines to allow paragraphs
  A fullstack developer with 3 years of experience and skills in a variety of programming languages, technologies, and development processes. Knowledge and understanding of <mark>Java</mark>, <mark>Angular</mark> and other related technologies. Experienced in analysis, design, development and testing applications. Passionate about cutting edge technologies and working in new expertise fields. Great problem solving and a unique team player. Able to adapt to a fast-paced environment, diagnose problems, and come up with fresh solutions.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    - Traveling
    - Reading
    - Cooking

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
